#!/bin/bash

# COULEURS
GREEN="\e[32m"
RED="\e[31m"
YELLOW="\e[33m"
NC="\e[0m"

# VÉRIFICATION ROOT
if [[ $EUID -ne 0 ]]; then
    echo "Utilisez sudo pour exécuter ce script"
    exit 1
fi
user=$(logname)
read -p "entrez votre adresse mail : " email
echo "export email=$email" >> /home/$user/.warnssh_env

echo "entrez votre mot de passe d'application (16 caractères) : "
read -s password
echo "$GREEN[INFO] $NCInstallation en cours..."

# INSTALLATION DES DÉPENDANCES
debconf-set-selections <<< "postfix postfix/mailname string your.hostname.com"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
apt-get install --assume-yes postfix mailutils libnotify-bin > /dev/null

sudo systemctl restart postfix

sudo cp warnSSH "/usr/local/bin/warnSSH"

# FICHIER SERVICE
sudo cat > /etc/systemd/system/warnssh.service <<EOF
[Unit]
Description=Un outil pour notifier les connexions SSH en temps réel

[Service]
ExecStart=/usr/local/bin/warnSSH
Restart=always
User=$user
Environment=DISPLAY=:0
Environment=HOME=$HOME
Environment=XDG_RUNTIME_DIR=/run/user/1000
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
Environment=XAUTHORITY=$HOME/.Xauthority

[Install]
WantedBy=multi-user.target
EOF

echo "[smtp.gmail.com]:587 $email:$password" > /etc/postfix/sasl_passwd
chmod 600 /etc/postfix/sasl_passwd

# MODIF FICHIER DE CONF POSTFIX
sed -i /^relayhost/d /etc/postfix/main.cf
echo "relayhost = [smtp.gmail.com]:587" >> /etc/postfix/main.cf
echo "smtp_use_tls = yes" >> /etc/postfix/main.cf
echo "smtp_sasl_auth_enable = yes" >> /etc/postfix/main.cf
echo "smtp_sasl_security_options =" >> /etc/postfix/main.cf
echo "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd" >> /etc/postfix/main.cf
echo "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt" >> /etc/postfix/main.cf

postmap /etc/postfix/sasl_passwd

systemctl daemon-reload
systemctl enable warnssh.service
systemctl restart warnssh.service
echo -e "\n$GREEN[INFO]$NC Installation terminée, veuillez relancer votre shell."
