#!/bin/bash

# COULEURS
GREEN="\e[32m"
RED="\e[31m"
YELLOW="\e[33m"
NC="\e[0m"

# VÉRIFICATION ROOT
if [[ $EUID -ne 0 ]]; then
    echo "Utilisez sudo pour exécuter ce script"
    exit 1
fi

# INSTALLATION DES DÉPENDANCES
debconf-set-selections <<< "postfix postfix/mailname string your.hostname.com"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
apt-get install --assume-yes postfix mailutils libnotify-bin > /dev/null

sudo systemctl restart postfix

sudo cp warnSSH "/usr/local/bin/warnSSH"

user=$(logname)
sudo cat > /etc/systemd/system/warnssh.service <<EOF
[Unit]
Description=Un outil pour notifier les connexions SSH en temps réel

[Service]
ExecStart=/usr/local/bin/warnSSH
Restart=always
User=$user
Environment=DISPLAY=:0
Environment=HOME=/home/$user
Environment=XDG_RUNTIME_DIR=/run/user/1000
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
Environment=XAUTHORITY=/home/$user/.Xauthority

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable warnssh.service
systemctl restart warnssh.service
echo -e "$GREEN[INFO]$NC Installation terminée"
